apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true