# Prometheus configuration for scraping metrics from API, ingestion, CLI, and ingest.py
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['192.168.137.171:8000']
  - job_name: 'ingestion'
    static_configs:
      - targets: ['192.168.137.171:8001']
  - job_name: 'cli'
    static_configs:
      - targets: ['192.168.137.171:8002']
  - job_name: 'ingest'
    static_configs:
      - targets: ['192.168.137.171:8003']